# Generated by Django 6.0.4 on 2026-05-30 06:59

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_country_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
