# Generated by Django 6.0.4 on 2026-06-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customer_address_alter_customer_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="display_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
