# Generated by Django 6.0.4 on 2026-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customer_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="promo_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
