# Generated by Django 6.0.4 on 2026-08-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customer_promo_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="promo_discount",
        ),
    ]
