# Generated by Django 6.0.4 on 2026-08-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_customer_promo_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="display_name",
        ),
    ]
