# Generated by Django 6.0.4 on 2026-08-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_customer_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercustomer",
            name="enabled",
        ),
    ]
