# Generated by Django 6.0.4 on 2026-08-26 20:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_contact_address_contact_city_contact_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=django_countries.fields.CountryField(default="", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
    ]
