# Generated by Django 6.0.4 on 2026-05-29 06:49

import checkout.models
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customer_country_delete_country'),
        ('products', '0002_product_product_image_url_alter_product_flavor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_code', models.CharField(default=checkout.models.generate_reference_code, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Cancelled')], default=0)),
                ('invoice_name', models.CharField(max_length=100)),
                ('invoice_surname', models.CharField(max_length=100)),
                ('invoice_phone', models.CharField(max_length=20)),
                ('invoice_address', models.CharField(max_length=255)),
                ('invoice_postcode', models.CharField(max_length=20)),
                ('invoice_city', models.CharField(max_length=100)),
                ('invoice_country', django_countries.fields.CountryField(max_length=100)),
                ('delivery_name', models.CharField(max_length=100)),
                ('delivery_surname', models.CharField(max_length=100)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_postcode', models.CharField(max_length=20)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_country', django_countries.fields.CountryField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0)),
                ('stripe_pid', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='checkout.order')),
            ],
        ),
    ]
