# Generated by Django 6.0.4 on 2026-05-31 16:54

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_country',
            field=django_countries.fields.CountryField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
