# Generated by Django 6.0.4 on 2026-06-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_payment_stripe_pid_order_stripe_pid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
