# Generated by Django 6.0.4 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0009_alter_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="promo_discount_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
