# Generated by Django 6.0.4 on 2026-08-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_customer_promo_discount"),
        ("checkout", "0010_order_promo_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="gift_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.contact",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gift_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_gift",
            field=models.BooleanField(default=False),
        ),
    ]
