# Generated by Django 6.0.4 on 2026-08-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checkout",
            "0011_orderitem_gift_contact_orderitem_gift_message_and_more",
        ),
        ("products", "0007_rename_comment_to_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
            ),
        ),
    ]
