# Generated by Django 6.0.4 on 2026-05-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flavor', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
