# Generated by Django 6.0.4 on 2026-06-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_product_image_url_alter_product_flavor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="flavor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chocolate", "Chocolate"),
                    ("vanilla", "Vanilla"),
                    ("fruity", "Fruity"),
                    ("caramel", "Caramel"),
                    ("nutty", "Nutty"),
                    ("special", "Special"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
