# Generated by Django 6.0.4 on 2026-06-10 07:18

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_flavor_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                default=products.models.generate_sku,
                max_length=255,
                unique=True,
            ),
        ),
    ]
