# Generated by Django 6.0.4 on 2026-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_images/backgrounds/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="can_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_images/cans/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first among featured products",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Show this product on the home page showcase"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="objects_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_images/objects/"
            ),
        ),
    ]
